-- ===================================================
-- ESQUEMA Y TABLAS PARA MÓDULO SISTEMAS TI (SQL SERVER)
-- ===================================================

CREATE SCHEMA TI;
GO

-- 1. TABLA DE CATÁLOGO DE ACTIVOS TI
CREATE TABLE TI.ACTIVO_TI (
    id_activo INT IDENTITY(1,1) PRIMARY KEY,
    codigo_patrimonial VARCHAR(50) UNIQUE NOT NULL,
    tipo_activo VARCHAR(50) NOT NULL, -- LAPTOP, CELULAR, MONITOR, TECLADO, MOUSE, TABLET, CARGADOR
    marca VARCHAR(100) NOT NULL,
    modelo VARCHAR(100) NOT NULL,
    numero_serie VARCHAR(100) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLE', -- DISPONIBLE, ASIGNADO, MANTENIMIENTO, BAJA
    id_empleado_asignado INT NULL,
    fecha_registro DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_ACTIVO_EMPLEADO FOREIGN KEY (id_empleado_asignado) REFERENCES dbo.EMPLEADO(id)
);
GO

-- 2. TABLA RELACIONAL E HISTORIAL DE CARGOS Y ASIGNACIONES
CREATE TABLE TI.CARGO_ASIGNACION (
    id_asignacion INT IDENTITY(1,1) PRIMARY KEY,
    id_activo INT NOT NULL,
    id_empleado INT NOT NULL,
    fecha_asignacion DATETIME DEFAULT GETDATE(),
    fecha_devolucion DATETIME NULL,
    estado_entrega VARCHAR(30) NOT NULL, -- NUEVO, BUENO, REGULAR
    observaciones VARCHAR(500) NULL,
    ruta_pdf_firmado VARCHAR(255) NULL,
    CONSTRAINT FK_CARGO_ACTIVO FOREIGN KEY (id_activo) REFERENCES TI.ACTIVO_TI(id_activo),
    CONSTRAINT FK_CARGO_EMPLEADO FOREIGN KEY (id_empleado) REFERENCES dbo.EMPLEADO(id)
);
GO

-- ÍNDICES DE RENDIMIENTO
CREATE INDEX IX_ACTIVO_TIPO ON TI.ACTIVO_TI(tipo_activo);
CREATE INDEX IX_ACTIVO_ESTADO ON TI.ACTIVO_TI(estado);
CREATE INDEX IX_CARGO_EMPLEADO ON TI.CARGO_ASIGNACION(id_empleado);
GO
